eureka.client.service-url.defaultZone=${EUREKA_URL:http://discovery-server:8761/eureka}

eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info

server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/eventsphere_events}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:eventsphere_user}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:eventsphere_pass}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect