server.port=8080
spring.application.name=api-gateway

# Service 1: user-service Route Configuration
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

# Discovery / Eureka Configuration
eureka.client.service-url.defaultZone=${EUREKA_URL:http://discovery-server:8761/eureka}
eureka.instance.prefer-ip-address=true

# Actuator Endpoints Exposure
management.endpoints.web.exposure.include=health,info